"""The stable launcher: `$NELIX_HOME/bin/nelix`, the one path an adapter ever names.

It is a DISPATCHER, not a symlink, for two reasons a symlink cannot serve: it has to pin the build
it resolved into the dispatched environment, and it has to explain itself when the core is not
installed. Both are the difference between "nelix is broken" and "run the bootstrap".

The dispatcher runs on whatever `python3` the system has — it executes BEFORE any nelix runtime is
on the path, so it may import nothing of ours and nothing third-party.
"""
import os
from pathlib import Path

PINNED_BUILD_ENV = "NELIX_PINNED_BUILD"

DISPATCHER = '''#!/usr/bin/env python3
"""nelix stable launcher — resolve the active build once, pin it, exec the runtime's own nelix.

Generated by launcher.py; do not edit. Reinstalled by `nelix launcher install`.
"""
import os
import sys

PINNED_BUILD_ENV = "NELIX_PINNED_BUILD"


# The cli_api "core or daemon unavailable" class. Deliberately the SAME number the installed CLI
# uses for that condition: an adapter seeing 3 need not care whether the launcher or the core it
# would have dispatched into produced it — the meaning is identical.
EXIT_UNAVAILABLE = 3


def _die(message):
    sys.stderr.write("nelix: " + message + "\\n")
    raise SystemExit(EXIT_UNAVAILABLE)


def main():
    home = os.environ.get("NELIX_HOME", "").strip() or os.path.join(
        os.path.expanduser("~"), ".nelix")
    home = os.path.abspath(home)
    current = os.path.join(home, "runtimes", "current")

    # ONE resolution. An activation (or a future GC) may repoint this at any instant; reading it
    # twice would let one process dispatch into a build it never verified.
    try:
        build = os.readlink(current)
    except OSError:
        _die("core not installed in " + home + " — run the nelix bootstrap "
             "(no runtimes/current to dispatch into)")
    build = os.path.basename(build.rstrip("/"))

    target = os.path.join(home, "runtimes", build, "venv", "bin", "nelix")
    if not os.path.exists(target):
        _die("the active build " + build + " is incomplete: " + target + " is missing — "
             "reinstall or activate another build")
    if not os.access(target, os.X_OK):
        _die("the active build " + build + " is not executable: " + target)

    env = dict(os.environ)
    env[PINNED_BUILD_ENV] = build
    os.execve(target, [target] + sys.argv[1:], env)


if __name__ == "__main__":
    main()
'''


def install(nelix_home) -> Path:
    """Write the dispatcher to <nelix_home>/bin/nelix atomically and return its path.

    Atomic because this file is what every adapter invokes: a half-written launcher is a broken
    installation for every host at once, so it is staged beside its destination and moved into
    place with os.replace, which is atomic within a filesystem.
    """
    bin_dir = Path(nelix_home) / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    dest = bin_dir / "nelix"
    tmp = bin_dir / "nelix.tmp"
    tmp.write_text(DISPATCHER, encoding="utf-8")
    os.chmod(tmp, 0o755)
    os.replace(tmp, dest)
    return dest
