from dataclasses import dataclass
from typing import Protocol


@dataclass
class ExecutorCapabilities:
    isolation_class: str          # "host" | "container" | "remote"
    can_attach: bool = False


@dataclass
class LeaderStatus:
    alive: bool
    exit_code: "int | None"
    signal: "int | None"
    status_available: bool   # False => dead but ptyprocess exposed no status


class ExecutorHandle(Protocol):
    def pump(self, timeout: float = 0.1) -> bool: ...
    def render(self) -> str: ...
    def write(self, data: str, timeout: "float | None" = None) -> None: ...  # raises errors.PtyWriteTimeout
    def is_alive(self) -> bool: ...
    def exit_code(self) -> "int | None": ...
    def leader_pid(self) -> "int | None": ...
    def leader_pgid(self) -> "int | None": ...
    def leader_status(self) -> "LeaderStatus": ...
    def finalize(self) -> None: ...
    def close(self) -> None: ...


class Launcher(Protocol):
    @property
    def capabilities(self) -> ExecutorCapabilities: ...
    def start(self, spec, cwd: str, cols: int, rows: int, dialog=None, transcript=None) -> ExecutorHandle: ...
    def stop(self, handle: ExecutorHandle) -> None: ...
