from dataclasses import dataclass
from typing import Protocol


@dataclass
class ExecutorCapabilities:
    isolation_class: str          # "host" | "container" | "remote"
    can_attach: bool = False


class ExecutorHandle(Protocol):
    def pump(self, timeout: float = 0.1) -> bool: ...
    def render(self) -> str: ...
    def write(self, data: str) -> None: ...
    def is_alive(self) -> bool: ...
    def close(self) -> None: ...


class Launcher(Protocol):
    @property
    def capabilities(self) -> ExecutorCapabilities: ...
    def start(self, spec, cols: int, rows: int) -> ExecutorHandle: ...
    def stop(self, handle: ExecutorHandle) -> None: ...
